homepage/urls.py
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

from rest_framework.routers import DefaultRouter
from .views import index, redirect_to_download, CategoryViewSet, ItemViewSet, DownloadViewSet


app_name = 'homepage'

router = DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'items', ItemViewSet)
router.register(r'downloads', DownloadViewSet)


urlpatterns = [  
    # 主页  
    path('', index, name='index'),
    path('api/', include(router.urls)),
    path('<str:app_name>-<str:system>-<str:architecture>/', redirect_to_download, name='redirect_to_download'),
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/homepage/images/favicon.ico')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

updatefetchWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls')),
    path('up/', include('upload.urls')),
    path('admin/', admin.site.urls),
]

upload/urls.py
from django.urls import path, re_path

from rest_framework.routers import DefaultRouter
from .views import redirect_to_random, handle_file_upload, delete_upload


app_name = 'upload'

urlpatterns = [
    path('', redirect_to_random, name='upload'),
    path('<str:random_str>/', handle_file_upload),
    path('<str:random_str>/delete/<int:file_id>/', delete_upload),
]

homepage/models.py
from django.db import models
from updatefetchWeb.settings import undefined_image_url, undefined_version, PLATFORM_CHOICES, ARCHITECTURE_CHOICES


class Category(models.Model):
    """每个分类的一些元信息"""
    title = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200, blank=True, default='')

    def __str__(self):
        """返回模型的字符串表示。"""
        return self.title


class Item(models.Model):
    """每个下载项的一些元信息"""
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)   # 在前层，实现未定义则划分为 未分类 的类别中，因为这里不能保证类被创建
    name = models.CharField(max_length=50, unique=True)
    image = models.URLField(blank=True, default=undefined_image_url)
    website = models.URLField(blank=True)
    version = models.CharField(max_length=50, blank=True, default=undefined_version)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """返回模型的字符串表示。"""
        return self.name


class Download(models.Model):
    """每个 item 在不同平台、不同架构下，对应着不同的下载链接"""
    item = models.ForeignKey(Item, related_name='downloads', on_delete=models.CASCADE)
    platform = models.CharField(max_length=20, choices=PLATFORM_CHOICES, default="windows")
    architecture = models.CharField(max_length=20, choices=ARCHITECTURE_CHOICES, default='amd64')
    link = models.URLField(unique=True)

    def __str__(self):
        """返回模型的字符串表示。"""
        return '-'.join([self.item.name, self.platform, self.architecture])

upload/models.py
from django.db import models
from datetime import datetime, timedelta

# Create your models here.
class Upload(models.Model):
    path = models.CharField(max_length=20)  # Random string for the path
    file_name = models.CharField(max_length=255)  # Original filename
    suffix_name = models.CharField(max_length=10, blank=True)  # File extension
    link = models.URLField()  # Download link from MinIO
    uploaded_at = models.DateTimeField(auto_now_add=True)  # Timestamp of upload

    def is_expired(self):
        return datetime.now() >= self.uploaded_at + timedelta(days=3)
    
    def is_photo(self):
        if self.suffix_name in {".png", ".jpg", ".jpeg", ".webp", '.gif', '.avif', '.svg'}:
            return True
        else:
            return False

homepage/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseNotFound

from .models import Category, Item, Download
from updatefetchWeb.settings import ALL_SYSTEM, ALL_ARCH, SYSTEM_LIST, ARCH_LIST, ALL_SYSTEM_ARCH

def index(request):
    categories = Category.objects.all()
    return render(request, 'homepage/homepage.html', {'categories': categories})


def redirect_to_download(request, app_name, system, architecture):
    """正确顺序应该是，名称-系统-架构"""
    # print(f"{app_name}-{system}-{architecture}")
    # 根据名称获取 Item 对象，不存在直接返回 404
    item = get_object_or_404(Item, name=app_name)

    # 只有规定的字段才处理
    if not (system in ALL_SYSTEM_ARCH and architecture in ALL_SYSTEM_ARCH):
        return HttpResponseNotFound('<h1>请使用规定的字段</h1>')
    # 经过调整，系统和架构不会颠倒，
    if system in ALL_SYSTEM and architecture in ALL_ARCH:
        pass
    elif system in ALL_ARCH and architecture in ALL_SYSTEM:
        system, architecture = architecture, system
    else:   # 加入是 name-win-win 这种，也直接报错
        return HttpResponseNotFound('<h1>系统和架构处有问题</h1>')

    # 这样就都是标准的架构名和系统名了
    for specific_system in SYSTEM_LIST:
        if system in specific_system['alias']:
            system = specific_system['standard_name']
            break
    for specific_arch in ARCH_LIST:
        if architecture in specific_arch['alias']:
            architecture = specific_arch['standard_name']
            break
    
    # print(f"{app_name}-{system}-{architecture}")
    # 获取与提供的系统和架构对应的 Download 对象
    download = get_object_or_404(Download, item=item, platform=system, architecture=architecture)

    # 重定向到实际的下载链接
    return redirect(download.link)


# API
from rest_framework import viewsets
from .serializers import CategorySerializer, ItemSerializer, DownloadSerializer


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class ItemViewSet(viewsets.ModelViewSet):
    queryset = Item.objects.all()
    serializer_class = ItemSerializer


class DownloadViewSet(viewsets.ModelViewSet):
    queryset = Download.objects.all()
    serializer_class = DownloadSerializer

upload/views.py
from django.shortcuts import render

# Create your views here.
import os, random, string
from .models import Upload
from django.shortcuts import render, redirect
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseNotFound

from updatefetchWeb.settings import upload_temporary_dir, minio_uploader


def generate_random_string(length=5):
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=length))

def redirect_to_random(request):
    random_str = generate_random_string()
    return redirect(f'/up/{random_str}/')


def handle_file_upload(request, random_str):
    if request.method == 'POST':
        file = request.FILES['file']
        filename = file.name
        file_path = upload_temporary_dir + filename
        
        fs = FileSystemStorage(location=upload_temporary_dir)
        fs.save(filename, file)
        # Upload to MinIO server
        try:
            minio_uploader.import_config(file_path, random_str)
            minio_uploader.run()
            links = minio_uploader.get_uploaded_files_link()
            link = links[0]
            # Save the object data in the database
            upload = Upload(
                path=random_str,
                file_name=os.path.splitext(filename)[0],
                suffix_name=os.path.splitext(filename)[1],
                link=link,
            )
            upload.save()
        except Exception as exc:
            print('Error occurred while uploading to MinIO:', exc)
            return HttpResponseNotFound('<h1>上传失败</h1>')
        # 上传完成后，删除本地文件
        os.remove(fs.path(filename))
        return redirect(f'/up/{random_str}/')
    
    uploads = Upload.objects.filter(path=random_str)
    return render(request, 'upload/upload.html', {'uploads': uploads, 'random_str': random_str})


def delete_upload(request, random_str, file_id):
    upload = Upload.objects.get(id=file_id, path=random_str)
    try:
        minio_uploader.delete(upload.path, upload.file_name + upload.suffix_name)
        upload.delete()
        return redirect(f'/up/{random_str}/')
    except Exception as exc:
        print('Error occurred while deleting from MinIO:', exc)
        return HttpResponseNotFound('<h1>删除失败</h1>')

homepage/templates/homepage/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'homepage/images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'homepage/images/favicon.ico' %}" type="image/x-icon">
    {% block extra_styles %}{% endblock %}
    <title>{% block title %}UpdateFetch Web{% endblock %}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .title {
            text-align: center;
        }
        .subtitle {
            text-align: center;
            font-size: 14px;
        }
        .divider {
            border-top: 1px dashed #000;
            margin: 20px 0;
        }
        .section {
            margin-top: 20px;
        }
        .section h2 {
            font-size: 24px;
        }
        .content {
            display: flex;
            flex-wrap: wrap;
        }
        .item {
            width: 30%;
            padding: 10px;
            box-sizing: border-box;
        }
        .item-image-width {
            width: 200px;
        }
        /* Add more styles as needed */

        /* 响应式设计：为手机和平板屏幕调整样式 */
        @media (max-width: 768px) {
            .content {
                display: flex; /* 维持弹性盒子布局 */
                flex-wrap: wrap; /* 允许内容换行 */
            }
            .item {
                width: calc(50% - 20px); /* 每个 item 占据行宽的一半减去 padding */
                margin: 10px; /* 添加 margin 来保证间隔 */
                box-sizing: border-box;
            }
            .item-image-width {
                width: 100%; /* 图片宽度自适应容器宽度 */
                height: auto; /* 高度自动调整保持图片比例 */
            }
        }
        
        /* 也可以添加其他断点，针对更小的屏幕进行调整 */
        @media (max-width: 480px) {
            .content {
                display: block; /* 在较小屏幕上堆叠元素而不是并排 */
            }
            .item {
                width: 100%; /* 每一项占满整个宽度 */
                padding: 10px;
                box-sizing: border-box;
            }
            .item-image-width {
                width: 100%; /* 图片宽度自适应容器宽度 */
                height: auto; /* 高度自动调整保持图片比例 */
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="title">
            <h1>{% block title_content %}{% endblock %}</h1>
            <p class="subtitle">by AhFei</p>
            <p class="subtitle">GitHub: <a href="https://github.com/ahfeil/updatefetchWeb">https://github.com/ahfeil/updatefetchWeb</a></p>
            <p class="subtitle"> <a href="{% url 'upload:upload' %}">网页暂存区</a> </p>
        </div>
        <div class="divider"></div>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

homepage/templates/homepage/homepage.html
{% extends 'homepage/base.html' %}

{% block title_content %}UpdateFetch Web{% endblock %}

{% block content %}
    {% for category in categories %}
    <div class="section">
        <h2>{{ category.title }}</h2>
        <div class="content">
            {% for item in category.items.all %}
            <div class="item">
                <h3>{{ item.name }}</h3>
                <img src="{{ item.image }}" class="item-image-width">
                {% if item.website %}
                <p><a href="{{ item.website }}">Official Site</a></p>
                {% endif %}                
                <p>Version: {{ item.version }}</p>
                <p>Update: {{ item.last_modified }}</p>
                <p>Downloads:
                    {% for download in item.downloads.all %}
                        <a href="{{ download.link }}" target="_blank">{{ download.platform }}({{ download.architecture }})</a>{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
{% endblock %}

upload/templates/upload/upload.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block title_content %}UpdateFetch Web - File Upload{% endblock %}

{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'upload/css/upload.css' %}">
{% endblock %}


{% block content %}
    <form action="{% url 'upload:upload' %}{{ random_str }}/" method="post" enctype="multipart/form-data" class="upload-form">
        {% csrf_token %}
        <div class="file-upload-container">
            <label for="file-input" class="file-select-btn">选择文件</label>
            <input id="file-input" type="file" name="file" style="display: none;">
            <button type="submit" class="upload-btn">上传</button>
        </div>
    </form>

    <div class="section">
        <h2>Temp Saved</h2>
        <div class="content">
            {% for upload in uploads %}
            <div class="item">
                <h3>{{ upload.file_name }}</h3>
                {% if upload.is_photo %}
                <img src="{{ upload.link }}" class="item-image-width">
                {% endif %}
                <p> <a href="{{ upload.link }}" target="_blank">Download</a> </p>
                <p> <a href="{% url 'upload:upload' %}{{ random_str }}/delete/{{ upload.id }}/">Delete</a> </p>
            </div>
            {% endfor %}
        </div>
    </div>

    <script>
        function deleteFile(fileId) {
            fetch(`{% url 'upload:upload' %}{{ random_str }}/delete/${fileId}/`, { method: 'POST' })
                .then(response => response.json())
                .then(data => {
                    if (data.message) {
                        alert(data.message);
                        window.location.reload();
                    } else {
                        alert(data.error);
                    }
                });
        }
    </script>
{% endblock %}